version: "3"

services:
  producer:
    build: ./app/producer
    container_name: producer
    environment:
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - AWS_REGION=${AWS_REGION}
    restart: always

  processor:
    build: ./app/processor
    container_name: processor
    environment:
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - AWS_REGION=${AWS_REGION}
    restart: always