from groq import Groq
import os
import re

# Initialize Groq client only if API key is provided
api_key = os.getenv("GROQ_API_KEY")
client = None
if api_key:
    client = Groq(api_key=api_key)

SYSTEM_PROMPT = """
You convert user questions into Prometheus queries.

STRICT RULES:
- Return ONLY a valid PromQL query.
- Do NOT return any explanations, markdown code blocks, or extra text.
- Do NOT use backticks around the query.

Available metrics:
- orders_processed_total (tracks total number of processed orders)
- high_value_orders_total (tracks processed orders with value > 5000)

Examples:
Q: high value orders per minute
A: rate(high_value_orders_total[1m])

Q: total processed orders
A: sum(orders_processed_total)

Q: rate of processed orders over 5 minutes
A: rate(orders_processed_total[5m])
"""

def local_keyword_translator(question: str) -> str:
    """
    Highly reliable, rule-based fallback translator to resolve PromQL queries 
    locally in case of Groq API rate limits, network failures, or missing credentials.
    """
    q_lower = question.lower()
    
    # 1. Determine base metric
    if any(k in q_lower for k in ["high value", "high_value", "expensive", "sales > 5000"]):
        metric = "high_value_orders_total"
    else:
        metric = "orders_processed_total"

    # 2. Determine aggregation / time-range
    if "per minute" in q_lower or "1 minute" in q_lower or "1m" in q_lower:
        return f"rate({metric}[1m])"
    elif "per hour" in q_lower:
        return f"rate({metric}[1h])"
    elif "over" in q_lower:
        # Extract time range if specified (e.g. over 5 minutes)
        match = re.search(r"over\s+(\d+)\s+(minute|min|m|hour|h|second|s)", q_lower)
        if match:
            val, unit = match.groups()
            unit_char = unit[0]
            return f"rate({metric}[{val}{unit_char}])"
        return f"rate({metric}[5m])"
    elif "rate" in q_lower or "speed" in q_lower:
        return f"rate({metric}[1m])"
    elif "total" in q_lower or "sum" in q_lower or "count" in q_lower:
        return f"sum({metric})"
    
    # Default safe fallback query
    return f"rate({metric}[1m])"


def validate_query(query: str) -> str:
    """
    Strict safety and sanitization layer. Ensures that the query generated by the LLM
    contains only safe, whitelisted characters and references valid whitelisted metrics.
    """
    if not query:
        raise ValueError("Generated query is empty")

    # Strip any enclosing backticks, quotes, or whitespace that LLMs sometimes generate
    query = query.replace("`", "").replace("'", "").replace('"', "").strip()

    # Allowed characters: alphanumeric, brackets, curly braces, arithmetic operators, comma, colon, dots
    if not re.match(r"^[a-zA-Z0-9_()[\]{}=,:+*/.\s\-]+$", query):
        raise ValueError("Query contains unsafe or illegal characters")

    # Metric whitelisting
    VALID_METRICS = ["orders_processed_total", "high_value_orders_total"]
    if not any(metric in query for metric in VALID_METRICS):
        raise ValueError("Query does not reference any valid system metrics")

    # Command injection or dangerous operators prevention
    blacklist = ["system", "os", "subprocess", "eval", "exec", "import", "rm", "sh"]
    if any(item in query.lower() for item in blacklist):
        raise ValueError("Query contains forbidden keywords")

    return query


def get_query_from_llm(question: str) -> str:
    """
    Translates a natural language question into PromQL.
    Falls back gracefully to local rule-based parsing on any failure.
    """
    if not question:
        return "rate(orders_processed_total[1m])"

    # If no Groq client is configured, immediately bypass to local parser (zero delay)
    if not client:
        return local_keyword_translator(question)

    try:
        response = client.chat.completions.create(
            model="llama3-8b-8192",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": question}
            ],
            temperature=0.1,  # Keep it highly deterministic
            max_tokens=50
        )

        query = response.choices[0].message.content.strip()
        return validate_query(query)

    except Exception as e:
        # Structured console fallback logging (SRE thinking)
        print(f"[LLM FALLBACK ALERT] Groq query translation failed: {str(e)}. Using local keyword parser.")
        return local_keyword_translator(question)