pipeline {
    agent any

    environment {
        REGISTRY = "933428634281.dkr.ecr.ap-south-1.amazonaws.com"
        API_IMAGE = "${REGISTRY}/task-manager-api:${BUILD_NUMBER}"
        PROCESSOR_IMAGE = "${REGISTRY}/task-manager-processor:${BUILD_NUMBER}"
        PRODUCER_IMAGE = "${REGISTRY}/task-manager-producer:${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh 'python3 -m pip install pytest requests fastapi uvicorn groq prometheus_client'
                sh 'PYTHONPATH=./app/api pytest app/api/test_api.py'
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t $API_IMAGE ./app/api'
                sh 'docker build -t $PROCESSOR_IMAGE ./app/processor'
                sh 'docker build -t $PRODUCER_IMAGE ./app/producer'
            }
        }

        stage('Push (Mocked for Demo)') {
            steps {
                // sh 'docker push $API_IMAGE'
                // sh 'docker push $PROCESSOR_IMAGE'
                // sh 'docker push $PRODUCER_IMAGE'
                echo "Successfully built images. Skipping AWS ECR Push for local demonstration."
            }
        }

        stage('Deploy (Mocked for Demo)') {
            steps {
                // sh 'kubectl set image deployment/api api=$API_IMAGE'
                // sh 'kubectl set image deployment/processor processor=$PROCESSOR_IMAGE'
                // sh 'kubectl set image deployment/producer producer=$PRODUCER_IMAGE'
                echo "Skipping live EKS deployment for local demonstration."
            }
        }
    }
}