apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: 933428634281.dkr.ecr.ap-south-1.amazonaws.com/task-manager-processor:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: aws-secret