apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      serviceAccountName: task-manager-sa   # 🔥 ADD THIS
      containers:
        - name: producer
          image: 933428634281.dkr.ecr.ap-south-1.amazonaws.com/task-manager-producer:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config